name: Linting, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Start Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: npm run build
        if: always()
      - name: Linting typescript
        run: npm run lint:ts
        if: always()
      - name: Linting scss
        run: npm run lint:scss
        if: always()
      - name: Unit testing
        run: npm run test:unit
        if: always()
      - name: Building storybook
        run: npm run build:storybook
        if: always()
      - name: Screenshot testing
        run: npm run test:ui:ci
        if: always()
